# Generated by Django 5.2.7 on 2025-11-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlist', 'Waitlisted')], default='pending', max_length=20)),
                ('student_first_name', models.CharField(max_length=100, verbose_name="Student's First Name")),
                ('student_last_name', models.CharField(max_length=100, verbose_name="Student's Last Name")),
                ('student_date_of_birth', models.DateField(verbose_name="Student's Date of Birth")),
                ('student_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, verbose_name="Student's Gender")),
                ('student_place_of_birth', models.CharField(max_length=200, verbose_name="Student's Place of Birth")),
                ('previous_school', models.CharField(blank=True, max_length=200, verbose_name='Previous School (if any)')),
                ('grade_applying_for', models.CharField(choices=[('preschool', 'Preschool'), ('nursery_1', 'Nursery 1'), ('nursery_2', 'Nursery 2'), ('kindergarten_1', 'Kindergarten 1'), ('kindergarten_2', 'Kindergarten 2'), ('primary_1', 'Primary 1'), ('primary_2', 'Primary 2'), ('primary_3', 'Primary 3'), ('primary_4', 'Primary 4'), ('primary_5', 'Primary 5'), ('primary_6', 'Primary 6'), ('jhs_1', 'JHS 1'), ('jhs_2', 'JHS 2'), ('jhs_3', 'JHS 3')], max_length=50, verbose_name='Grade Applying For')),
                ('guardian_first_name', models.CharField(max_length=100, verbose_name="Guardian's First Name")),
                ('guardian_last_name', models.CharField(max_length=100, verbose_name="Guardian's Last Name")),
                ('guardian_relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('grandparent', 'Grandparent'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('other', 'Other')], max_length=50, verbose_name='Relationship to Student')),
                ('guardian_phone', models.CharField(max_length=20, verbose_name="Guardian's Phone Number")),
                ('guardian_email', models.EmailField(max_length=254, verbose_name="Guardian's Email Address")),
                ('guardian_address', models.TextField(verbose_name="Guardian's Address")),
                ('guardian_occupation', models.CharField(max_length=100, verbose_name="Guardian's Occupation")),
                ('emergency_contact_name', models.CharField(max_length=100, verbose_name='Emergency Contact Name')),
                ('emergency_contact_phone', models.CharField(max_length=20, verbose_name='Emergency Contact Phone')),
                ('emergency_contact_relationship', models.CharField(max_length=50, verbose_name='Emergency Contact Relationship')),
                ('medical_conditions', models.TextField(blank=True, verbose_name='Medical Conditions/Allergies (if any)')),
                ('special_requirements', models.TextField(blank=True, verbose_name='Special Educational Requirements (if any)')),
                ('additional_notes', models.TextField(blank=True, verbose_name='Additional Notes')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
